### ISSUE TITLE
What to buy 

### ISSUE THREAD

**Issue by themoddedcube** [Tommrodrigues/homebridge-web-sprinkler#4]
Hi in my last post I was asking for help with integration, but in this post I need to know what to buy first, I have 8 zone sprinkles currently, so if I buy this board, [https://www.amazon.com/HiLetgo-Internet-Development-Wireless-Micropython/dp/B010O1G1ES](url), and 2 packs of these relays, [https://www.amazon.com/3V-Relay-Module-Optocoupler-Development/dp/B01M0E6SQM/ref=sr_1_1_sspa?dchild=1&keywords=8x+esp8266+relay&qid=1608826792&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFWTldITDNJSDYwOEQmZW5jcnlwdGVkSWQ9QTAyNDI4NzYzMkdXVjJVQ0VGMEg3JmVuY3J5cHRlZEFkSWQ9QTA1NTM5OTQ2MTFYWFQ3NDc2TVYmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl](url), would I be fine or do I need to buy anything else?

**Comment by themoddedcube** [comment]
Sorry for formatting still a bit new to github!

**Comment by phenotypic** [comment]
Hi again, I'd advise against buying parts from Amazon due to the comparatively extortionate pricing when compared to AliExpress or similar sites.

The ESP8266 board you linked is indeed the one the script was designed for, and whilst the relays you linked should work fine, it's highly inefficient to use multiple individual relays for an application like this. Instead, use a multi channel relay board with the correct voltage specifications.

Other than that and a couple of dupont cables- assuming you have a standard AC sprinkler zone setup and you know what you're doing with the wiring- that's all you'll need for this project.

Take a look at these items on AliExpress: [ESP8266 CP2102](https://a.aliexpress.com/_mP0fY6V) and [3.3V 8 channel relay board](https://a.aliexpress.com/_mtb85q1). I can't vouch for these sellers though and you might find better prices shopping around, but hopefully that helps answer your question.
